### ISSUE TITLE
Consumer Group Picks Messages from Beginning

### ISSUE THREAD

**Issue by surendragalwa** [spring-cloud/spring-cloud-stream-binder-kafka#1016]
I had a kafka consumer annotated with `StreamListener` without any group id. Now when I added the group-id via `spring.cloud.stream.bindings.input.group` it started listening all the older messages from beginning which were already consumed by this consumer when it did not have the group-id.

How can I configure it to pick only the unprocessed messages which were not picked before?

I tried adding `spring.cloud.stream.bindings.input.startOffset` to latest and `resetOffsets`  to true but it didn't work.And I still see `auto.offset.reset=earliest` in consumer logs. 

Thanks in advance. :)

**Comment by surendragalwa11** [comment]
Updated: I tried setting `resetOffsets` to true but doesn't work.

**Comment by sobychacko** [comment]
@surendragalwa When you start a consumer using the binder without a `groupId`, an anonymous group is created behind the scenes and by default, it always starts from the latest offset. When this consumer is restarted, it is treated as a brand new consumer (since its using a new anonymous group id) and starts from the latest offset again. On the other hand, when you provide the `group` using the binding property, this group id is kept statically between restarts and treated as the same consumer. When you provide the `group`, the default mechanism to start is from the `earliest` offset (using the kafka consumer property `auto.offset.reset` behind the scenes). You can override this using the `latest` value. However, there is a caveat. If the consumer already started to process any offsets, then `auto.offset.reset` does not have any impact. It simply ignores this value and continues from the last committed offset. I think this is what you are running into. You provided a `group` name and started to process some records. Then you provided the `latest` value for `startOffset` but the value got ignored since there are previously committed offsets in the consumer. You can create a new consumer with another group and provide the `latest` value for starting offset and that should only process starting from the latest records.

**Comment by garyrussell** [comment]
For an existing group, to reset the offsets based on the `startOffset` setting, set the `resetOffsets` property to `true`.

https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.1.0/reference/html/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties

>**resetOffsets**
>Whether to reset offsets on the consumer to the value provided by startOffset. Must be false if a KafkaRebalanceListener is provided; see Using a KafkaRebalanceListener.

>Default: false.

**Comment by garyrussell** [comment]
What version are you using? This works as expected for me; it only receives records published while it is running...

```java
@SpringBootApplication
public class Kbgh1016Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh1016Application.class, args);
	}

	@Bean
	Consumer<String> input() {
		return System.out::println;
	}

}
```
```properties
spring.cloud.stream.bindings.input-in-0.group=kbgh1016
spring.cloud.stream.kafka.bindings.input-in-0.consumer.start-offset=latest
spring.cloud.stream.kafka.bindings.input-in-0.consumer.reset-offsets=true
```
$ kafka-console-producer --broker-list localhost:9092 --topic input-in-0
>foo
>foo
>bar // stop app before this one
>bar // start app after this one
>foo
>
```

First run:
```
foo
foo
```
Second run:
```
foo
```

**Comment by surendragalwa** [comment]
I am using `Greenwich.SR1` version. I have tried setting below properties

`
spring.cloud.stream.bindings.input.consumer.startOffset=latest
spring.cloud.stream.bindings.input.consumer.resetOffsets=true
`
Consumer is listening to input topic via @StreamListener.

**Comment by surendragalwa** [comment]
@garyrussell I want to listen all the unconsumed/unprocessed messages neither just the message while it is running nor all the processed messages from beginning.

**Comment by surendragalwa** [comment]
When I set `spring.cloud.stream.kafka.binder.configuration.auto.offset.reset=latest` it doesn't pick the already processed records from beginning and start picking the messages which are being sent after the consumer restart.

However in this case, I miss those unprocessed messages which were send in between the consumer stop and start phase.

**Comment by surendragalwa11** [comment]
Here is my sample code https://github.com/surendragalwa11/spring-cloud-stream-kafka-consumer

**Comment by garyrussell** [comment]
So don't set `resetOffset`. What you want is the default behavior (once the consumer has read at least one record).

**Comment by surendragalwa11** [comment]
In that case in doesn’t pick the messages which were sent between the consumer stop (stop the consumer as it doesn’t have the consumer group Id set) and consumer start (consumer with fresh group I’d).

**Comment by surendragalwa11** [comment]
It doesn’t work first time when we a fresh set group I’d on a consumer which doesn’t have any group I’d set before.

**Comment by garyrussell** [comment]
That's how Kafka is designed. A new group starts at the earliest or latest. An existing group starts at the last commit.

If you want to position a new group someplace else, you would need to store the partitions/offsets elsewhere, you can then reposition the consumer by adding a `KafkaBindingRebalanceListener` `@Bean` and perform seeks on the `Consumer` in `onPartitionsAssigned` - but you need to be careful to only do it when the consumer has no committed offset for a particular partition because it can be called multiple times (when rebalances occur).

**Comment by surendragalwa11** [comment]
Ok, thanks. You mean this needs to be setup separately or the offset needs to moved/adjusted manually before the first run for the new consumer I’d?

**Comment by garyrussell** [comment]
Yes; if Kafka doesn't have a committed offset for a consumer, the only options are earliest or latest; anything else needs manual positioning.

Your use case is a little unusual, but it can be done by adding your own code to do the repositioning.

**Comment by surendragalwa11** [comment]
Thanks a ton @garyrussell

**Comment by sobychacko** [comment]
Closing the issue.
