### ISSUE TITLE
A lot of logs are produced due to metrics

### ISSUE THREAD

**Issue by rodion-fisenko** [spring-cloud/spring-cloud-stream-binder-kafka#1107]
Hi!

I found an issue due to which produces a lot of redundant logs like this:
`ConsumerCoordinator: [Consumer clientId=consumer-progress-pass-4, groupId=progress-pass] Found no committed offset for partition bingoblitz_app_progress_pass_steps_passed-1`

After some investigation, I found that the issue can be reproduced in the following conditions:
1. Use just initialised partition which has not received any messages yet. It this case the partition doesn't have committed offset;
2. Offset auto commit should be disabled (value of the property `spring.cloud.stream.kafka.binder.consumer-properties.enable.auto.commit` should be `false`);
3. Micrometer metrics are enabled (the bean `io.micrometer.core.instrument.MeterRegistry` exists in application context).

In this case the logs like described above will be produced every 60 seconds for each partition with no committed offset.

It happens because after merging of this PR (https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/965) some metrics collect every 60 seconds. 
As I see in the code the class `KafkaBinderMetrics` [create](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/54ac274ea32997221c5ca3c6c4ae7605345047a1/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetrics.java#L197) new consumer to calculate topic group lag. Offsets for this consumer cannot be auto reset to proper values (0 in this case) like it happens to usual consumers. 

Like a workaround to fix this issue we can use one of this options:
 1. Disable logs with level below `ERROR` for `org.apache.kafka.clients.consumer.internals.ConsumerCoordinator` logger;
2. Set the following property `spring.cloud.stream.kafka.binder.consumer-properties.enable.auto.commit: true` to enable auto commit. But this option [is not preferable](https://docs.spring.io/spring-kafka/reference/html/#committing-offsets), as it [can lead to problems](https://newrelic.com/blog/best-practices/kafka-consumer-config-auto-commit-data-loss).

Do you have a plan somehow to rework KafkaBinderMetrics to fix the issue? 

**UPD**
I found more suitable solution to avoid this issue. 

If we set the value of the property ContainerProperties.assignmentCommitOption to ALWAYS then uncommitted offsets be automatically committed during first partition assignment. 

To do it we should provide the following bean:

```
@Bean
public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
    return (container, dest, group) ->
        container.getContainerProperties()
            .setAssignmentCommitOption(ContainerProperties.AssignmentCommitOption.ALWAYS);
}
```

**Comment by garyrussell** [comment]
Why not change the log level of `o.a.k.c.c.internals.ConsumerCoordinator` to WARN?

**Comment by sobychacko** [comment]
@rodion-fisenko Please follow the suggestion from @garyrussell above by changing the log level in `ConsumerCoordinator` to `WARN`.  For more information on this reasoning see [this](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1123#issuecomment-902909179).  See also this [commit](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/ba2c3a05c9af6eea1b127c0aac899db735eb0290) where a single call to `committed()` is now used instead of invoking it per partition.  Closing this issue.

**Comment by st-h** [comment]
We have been trying out version 3.1.4 in order to get rid of this issue, however we still see the same amount of logs being produced. I also noticed that there seems to be an issue where micrometer does not provide up to date metrics when deploying our app with a recent spring-cloud-stream-binder-kafka dependency. Strangely this can be fixed by deploying a second instance to Kubernetes - then those missing metrics suddenly appear all at once.
