### ISSUE TITLE
Address Kafka Streams state machine changes introduced in KIP-696

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#1110]
[KIP-696](https://cwiki.apache.org/confluence/display/KAFKA/KIP-696%3A+Update+Streams+FSM+to+clarify+ERROR+state+meaning) made some changes in the way the error state in the Kafka Streams state machine is interpreted. 

See this [blog](https://blogs.apache.org/kafka/entry/what-s-new-in-apache5
) for more details (look under Kafka Streams section for KIP-696). With this change, the ERROR state is no longer considered a terminal state and the application may choose to stay alive and continue processing. This brings some issues in the binder in terms of backward compatibility. In the versions of Kafka streams prior to 2.8.0, the default behavior was that the client terminates if there is an uncaught error. Applications written with that assumption will fail with the change introduced by KIP-696 in Kafka Streams 2.8.0. This is especially a problem for the health check indicator in Kafka Streams binder. We should add an `UncaughtExceptionHandler` that restores the default behavior of previous versions - i.e. terminating the Kaka Streams client if there is an uncaught error. Users still have the option to override this by providing a custom `UncaughtExceptionHandler` in the application. See [this](https://kafka-tutorials.confluent.io/error-handling/kstreams.html) for more details.

**Comment by jmelby70** [comment]
@sobychacko This seems to have broken the ability to override with a custom StreamsUncaughtExceptionHandler. In earlier versions, we were able to override using:
```
@Bean
    public StreamsBuilderFactoryBeanConfigurer streamsCustomizer() {
        return factoryBean -> factoryBean.setStreamsUncaughtExceptionHandler(nimbusStreamsUncaughtExceptionHandler);
    }
```

However, since the StreamsBuilderFactoryBean gets created and this gets set BEFORE the StreamsBuilderFactoryManager.start() is run, it replaces the custom exception handler with the function you set here to always SHUTDOWN_CLIENT. I am not finding a way to get around this--I think StreamsBuilderFactoryManager.start() should check to see if streamsBuilderFactoryBean.getStreamsUncaughtExceptionHandler() is null before setting the default one.

**Comment by sobychacko** [comment]
@jmelby70 This repository has been migrated to the core Spring Cloud Stream [repository](https://github.com/spring-cloud/spring-cloud-stream). In addition, this is a closed issue. Could you create a new issue in core and link it from there? Thanks!
