### ISSUE TITLE
Make health indicator configurable by the users

### ISSUE THREAD

**Issue by magnusLechner** [spring-cloud/spring-cloud-stream-binder-kafka#1165]
Starting point is this [Stackoverflow question](https://stackoverflow.com/questions/69821547/actuator-health-does-not-detect-stopped-binders-in-spring-cloud-stream).
Customizing the health indicator allows users to tailor the health status to their specific use case.

Use case example:
We implemented some kind of circuit breaker which stops the binding after the processor could not process x messages in a row or y messages for a given time period in order to prevent flooding our error queues. When a binding is stopped we want to be alerted.
Our applications are monitored by Icinga using `actuator/health` as default monitoring endpoint and switching to another endpoint is not easily done. Therefore we want to enrich the health details by adding additional information regarding the state of the binders.

**Comment by sobychacko** [comment]
@magnusLechner After looking at this requirement a bit further, here is where we stand. 

The Kafka Streams health indicator only considers `KafkaStreams` objects that are presently running. We can change this so that the health check will indicate the status for all. For example, let's say a processor is in the middle of a rebalance, with the current code, you will not get the status for this processor because it is not running while you checked the health. We could fix this problem, but what you are running into is completely different. In Kafka Streams binder, when a binding is stopped, the underlying `KafkaStreams` object is completely gone. Next time you start the same binding, a brand new `KafkaStreams` object will be created. Thus, from the health check perspective, while the binding is stopped, there is no associated `KafkaStreams` to it and you will not get a health status. 

With that said, I think we can accommodate this use case by making a few changes. First of all, we will need a new property to enable health checks for any stopped `KafkaStreams` objects since the application started. We probably need to cache these stopped `KafkaStreams`. Then, when a health check is initiated, we can provide a simple `DOWN` status for the processor. The only thing that we need to be careful of here is that if the processor is running now, we should remove this previously stopped `KafkaStreams` from the internal cache so that the health check will not erroneously report this as `DOWN`. When opting into this feature, the overall health of your system (the top-level status on the query response) will be `DOWN`. You can then drill down into the `JSON` structure to query the details. 

Please let us know what you think about this design suggestion, then we can take this further for implementation.

**Comment by magnusLechner** [comment]
It looks like this will help us a lot. We assume that you should be able to clean the cache, when the binding comes back too RUNNING, based on the ID of the binding. So for us, this is the solution to go with.

If you need someone to test the changes, we can provide you with feedback :) Thanks so far.

**Comment by sobychacko** [comment]
@magnusLechner I have a [PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1175) for this issue.
