### ISSUE TITLE
Spring Cloud Stream binder

### ISSUE THREAD

**Issue by abdulshaikh76** [spring-cloud/spring-cloud-stream-binder-kafka#1180]
how does actuator  work for health check of spring cloud binder ?  

when kafka server is down , of my consume application the actuator health check showing me that it is down  . I would like to write my own custom health check for Eureka server to update the same status . so  i would like to understand the implementation of actuator/health check .

**Comment by sobychacko** [comment]
@abdulshaikh76 Currently, the health indicator in the Kafka binder is not conditional. If you want to write your own custom health indicator, then we need to change the [current configuration](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderHealthIndicatorConfiguration.java#L46) so that it is only included conditionally. Then you can write your own implementation. For a template on that, see the [default implementation](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java). When you define a bean for this in your configuration, make sure to add `@ConditionalOnEnabledHealthIndicator("binders")` so that Spring Cloud Stream will discover and enable it.

**Comment by sobychacko** [comment]
@abdulshaikh76 See the referenced [PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1182) above. Take a look at the documentation in the commit to see the details on how you can exclude the default implementation and add yourown.
