### ISSUE TITLE
Spring Boot web endpoints are queryable before HostInfo becomes available

### ISSUE THREAD

**Issue by TiewKH** [spring-cloud/spring-cloud-stream-binder-kafka#1185]
I was advised in my [StackOverflow question](https://stackoverflow.com/questions/70492182/spring-cloud-stream-with-kafka-interactive-query-wait-for-kafka-streams-to-ini) to post this as an issue here.

When my Spring Boot application starts, it exposes the web endpoints before HostInfo and state store becomes available. Thus, users will face exceptions when calling the endpoint in that period of time.

Is this the expected behaviour? 

Versions:
Spring Boot 2.6.2
Spring Cloud Stream, Spring Cloud Stream Binder Kafka Core, Spring Cloud Stream Binder Kafka Streams 3.2.1
Spring Kafka 2.8.1

**Comment by sobychacko** [comment]
@TiewKH This is now fixed in main and `3.1.x`. Basically, the same retry properties mentioned [here](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.2.1/reference/html/spring-cloud-stream-binder-kafka.html#_interactive_queries) for `maxAttempts` and `backoffPeriod` can be used for retrying the hostinfo methods now. See this [commit](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/3770db7844d47aa0fa450d6a5792fca58a02f810) for more details.
