### ISSUE TITLE
Support late binding for Kafka

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#12]
Moved from: https://github.com/spring-cloud/spring-cloud-stream/issues/590

Originally created by @vsrahul82:

Our spring boot apps try to connect to the Kafka servers at the time of application startup. If the Kafka server is down or name is wrongly spelled, the application does not startup. Is there a way to prevent the spring boot app from trying to connect to Kafka server so that application starts up successfully?

**Comment by matanshukry** [comment]
Looking forward for this feature as well

**Comment by codependent** [comment]
+1 for this feature

**Comment by EvilJinious1** [comment]
Any idea when this will be supported?  If I run an integration test on a build server, it will fail due to the lack of zookeeper infrastructure present.  This particular integration test is intended to test that we can load the context. If we use the rabbitMQ binding then it works even through rabbitmq is not present.

Any way to disable it somehow.  I hate to have to disable all these tests as they are handy to see if we screwed up things.

**Comment by yrobert** [comment]
I would be interested to get this feature too

**Comment by ulrich-h-da** [comment]
I'd be glad to use this feature in my integration tests

**Comment by LittleShrimp1987** [comment]
if we get a switch, it would be perfect.

**Comment by garyrussell** [comment]
Looks like there are two issues being discussed here.

- late binding (detect the broker is down and do the provisioning later, perhaps on a schedule)
- allow integration tests to "pass" when there is no broker - I don't really understand how that will help - surely an integration test without a broker can never pass - spring-kafka-test provides the `KafkaEmbedded` JUnit rule which can be used in integration tests [sample app here](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/test-embedded-kafka).

This issue is to address the first of these.

**Comment by Tal24** [comment]
Our MS try to connect to Kafka every 30 seconds (re-try), but still the service is not up until kafka is up, should this be implemented? because we want the service to be up even if kafka is down and the late binding (re-try) should be under the hood every 30 seconds

**Comment by cforce** [comment]
@garyrussell  Was KGH-12 https://github.com/sobychacko/spring-cloud-stream/commit/54abf564fd58f92d2b67c7202877fdfe26ce59c6 a solution to setup late binding? 
Do we need to cfg autoStartUp() for the Kafka Output or InputBindingLifecycle to false, so application will late bind and then i need to do start() on that bean on ApplicationReadyEvent ? Howto be fast up/non blocking and then do retries with  timeout?

**Comment by garyrussell** [comment]
@cforce Please don't ask questions on old, closed, issues. In any case, GitHub issues are not for asking questions.

Ask questions on Stack Overflow, tagged with spring-cloud-stream.

**Comment by sweelam** [comment]
Is there any solution for this requirement?

**Comment by Xyaren** [comment]
There isn't just no documentation about this. 
Late binding is not working properly due to all the retries and timeouts taking several minutes before "giving up".

**Comment by matanshukry** [comment]
@Xyaren I didn't find any documentatino about it, but it does seem to work from a few minutes of trying it.
Want to explain the problem / open a new issue ?
