### ISSUE TITLE
It should be possible to set retention.bytes or retention.ms when creating a topic

### ISSUE THREAD

**Issue by hekonsek** [spring-cloud/spring-cloud-stream-binder-kafka#153]
Hi @mbogoevici,

Currently there is no way to specify topic config to use when creating new topic. I think it would be awesome to have an ability to say something like...

```
spring.cloud.stream.kafka.topics.foo.retention.ms = 604800000
spring.cloud.stream.kafka.topics.foo.retention.bytes = 200000
```

...to indicate retention limits that should be applied by broker admin utility when creating new topic `foo`. 

It would be nice to support other topic config options as well in the future, but retention limits would be nice starting point IMHO as this is probably the most popular config option applied to new topics.

I can prepare a PR with such addition, but I just wanted to verify that this is something you find useful.

Thanks!

**Comment by ilayaperumalg** [comment]
@hekonsek Thank you for your willingness to contribute! This would be a great addition I believe. I am sure @mbogoevici would give a big +1. 

Currently, we don't set all topic config apart from few specific properties and I believe [this]((https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L213) is where we need to pass the topic config.

We could probably add a generic way to pass all the topic configuration so that we don't have to support only the explicit ones.

**Comment by hekonsek** [comment]
@ilayaperumalg Many thanks - I think we might dig into details of possible implementation as soon as @mbogoevici confirms that this is something that is worth creating pull request. :)

**Comment by mbogoevici** [comment]
@hekonsek Sure thing - that would be a very welcome contribution, thanks!

**Comment by hekonsek** [comment]
Cool! 

So the best approach that comes to my mind would be to create inner class `KafkaExtendedBindingProperties.TopicProperties` that can hold topic configuration (for example `retentionMs`). Then add `Map<String,TopicProperties> topics` property to the KafkaExtendedBindingProperties, so we could set topic properties like `spring.cloud.stream.kafka.topics.foo.retentionMs`.

Then we should access topic configuration from here - https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L213 . And pass those properties to the admin util.

I was tempt to propose generic map/properties holder instead of listing each config option (like `retentionMs`), but that would mean that for example IntelliJ users won't be able to take advantage of options autocompletion. So I think that it is better to go into an explicit list of available configuration settings.

What do you think?

**Comment by sobychacko** [comment]
@hekonsek your design sounds reasonable. Please issue a PR and then we can review it further. Keep in mind that there is a discussion around making some potential changes in the provisioner API. See this issue: https://github.com/spring-cloud/spring-cloud-stream/issues/976. However, the scope of that issue is not very well defined at the moment and I am not sure if it's going to change in 1.3 time frame. So, I think you are good for raising a PR and start the review process.

**Comment by hekonsek** [comment]
OK. I will create a pull request and link it here.

Cheers!

**Comment by sukrit007** [comment]
Has there been any progress on this?

**Comment by sobychacko** [comment]
Topic level properties can be passed through the topic provisioner to admin using the binding level properties. If you have a binding named `input` and if its a consumer binding, then this is how you may use it.
`spring.cloud.stream.kafka.bindings.input.consumer.topic`.

`replicationFactor` abnd `replicaAssignments` are supported by default. Any other properties need to use the following format.
`spring.cloud.stream.kafka.bindings.input.consumer.topic.properties.retention.ms`, 
`spring.cloud.stream.kafka.bindings.input.consumer.topic.properties.max.message.bytes` etc.

See [this class](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaTopicProperties.java) for more details.

If you have a producer binding named `output`, then replace `consumer` with `producer`. 
For e.g. `spring.cloud.stream.kafka.bindings.output.producer.topic`.

If you are using it as part of the Kafka Streams binder, then use the prefix `spring.cloud.stream.kafka.streams.bindings...`
