### ISSUE TITLE
Upgrading to Kafka 11.0.0 client

### ISSUE THREAD

**Issue by michael-barker** [spring-cloud/spring-cloud-stream-binder-kafka#186]
Is it safe to upgrade from the 10.1.1 client version to 11.0.0?

I'm able to use the the 10.1.1 Kafka client version to consume message from Kafka 11 without native Kafka headers.  However when there are native headers the Kafka client goes into an infinite loops trying to process a message.  This seems like an issue with the Kafka client and not the Kafka stream binder.

I tried using the 11.0.0 client with Kafka stream binder and I'm able to consume messages with native Kafka headers but of course I don't get the headers in my Spring Cloud Stream message which is much better than going into an infinite loop.  Are there any obvious issues at this point if one were to use the 11.0.0 Kafka client with the stream Kafka binder?

**Comment by sobychacko** [comment]
@michael-barker we can't officially upgrade to the `0.11.0.0.` client until `spring cloud stream` 
2.0 timeline. This is because of spring boot 1.5.x will override to a 0.10 based client (we can't upgrade to boot 2.0 until spring cloud stream 2.0). But, that doesn't mean that you can't try to upgrade it on your end. In your custom application, if you have a use case that requires the 0.11.x client, you can certainly try to upgrade.

**Comment by michael-barker** [comment]
@sobychacko Any idea what a rough timeline would be when the binder would support the 11 client?  Spring Boot 2 is due in November so I'm guessing it won't be for at least some time after that.

The reason I ask is that we have several teams using Spring Kafka and a couple using Spring Cloud Stream.  I much prefer Spring Cloud Stream but with others wanting to upgrade to Kafka 11 and Spring Kafka supporting 11 pretty soon it makes it a bit harder for me to make the case for Spring Cloud Stream adoption on our teams.

**Comment by garyrussell** [comment]
@michael-barker spring-kafka 1.3 (and 2.0) will be released next month; they support transactions and headers with the 0.11 client.

I am working on a binder that will work with 1.3; but it won't be part of the SCSt release train; we plan on releasing it as a stand-alone artifact (jar) which users can pull in instead of the existing binder. The initial work is [here](https://github.com/garyrussell/spring-cloud-stream-binder-kafka/commits/0.11).

I would expect to have the binder available soon after the 1.3 GA next month.

It will be merged back into the main project and be part of the release train for 2.0 (based on spring-kafka 2.0).

**Comment by michael-barker** [comment]
Thanks @garyrussell, that's great to hear!  Where can I check for an announcement on when that's published?

**Comment by sabbyanandan** [comment]
Hi, @michael-barker. Please keep an eye on [1.3.0.RC1](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/milestone/14) release marker. The GA release is planned for next month, too. There'll be release-blogs for the incremental milestones - you could subscribe to the [feeds](https://spring.io/blog).

**Comment by garyrussell** [comment]
@michael-barker there's a build snapshot of the 0.11 binder in spring's snapshot repo. Note the artifact name is ...kafka11


http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-stream-binder-kafka11/1.3.0.BUILD-SNAPSHOT/ We should have a milestone in a week or so with GA soon after.

**Comment by michael-barker** [comment]
It looks like the 11 binder is now GA.  Is it safe to override the the stream version in the Dalston release train with the Ditmars release and the Kafka 11 binder?

**Comment by sabbyanandan** [comment]
Yes - it was released yday - we will be promoting the releases soon. And yes, you can override the dependencies - please let us know if you see any issues with it.

**Comment by michael-barker** [comment]
Thanks!  We'll be using it very soon.
