### ISSUE TITLE
Add kafka-header property to accept trusted packages

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#195]
This is targeted to be on 2.x and backport it to 0.11 branch.

**Comment by sobychacko** [comment]
@garyrussell In 1.3.0 version of `scst`, the content-type header value is always converted to a String - https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/MessageSerializationUtils.java#L58.
Because of that the `DefaultKafkaHeaderMapper` will accept that as a trusted package since `java.lang.*` is trusted by default. Since the 0.11 binder depends on 1.3 scst, this issue does not look like a problem.

**Comment by garyrussell** [comment]
Ah; ok; makes sense; thanks.

**Comment by sobychacko** [comment]
Fixed via 7344bed0489a2846f8e009caadfffbd12b841df2
