### ISSUE TITLE
Reinstate static partitioning in Kafka biner

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#31]
By default, Kafka binder currently provide dynamically allocated/rebalanced partitions. We need a way to tell the binder to use static partitioning. It is desirable to have two flavors of static partitioning.

1. Use a modulo based approach (partition % instance count)
2. Use fixed set of partitions.

**Comment by sabbyanandan** [comment]
This is already supported.

**Comment by dvsridhar** [comment]
Is this available in **Brooklyn.RELEASE,**  we are noticing static portioning is not working as expected. 
we are setting the following JVM arguments as part of each microservice boot up ( -Dspring.cloud.stream.instanceIndex=(0..1) -Dspring.cloud.stream.instanceCount=2) and all the message getting hand over dynamically. 

Also, according to M1 release notes (https://spring.io/blog/2016/08/26/spring-cloud-stream-brooklyn-m1-is-available) the static partition feature will be available in the final release.  Do we know what's that release would be? Because this feature used to work with 0.8 consumer but not with the new version anymore.

**Comment by mbogoevici** [comment]
Hi @dvsridhar, 

Please use the `autoRebalanceEnabled` option of the Kafka Binder http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/htmlsingle/#_kafka_consumer_properties.

Please open a new issue if you need further support.

**Comment by dvsridhar** [comment]
Awesome that works. Thank you very much for all the help.
