### ISSUE TITLE
KafkaBinderMetrics are not exported with Spring Boot 2.0

### ISSUE THREAD

**Issue by urgelacko** [spring-cloud/spring-cloud-stream-binder-kafka#318]
I am using Spring Cloud stream 2.0.0-RC1 with `micrometer-registry-graphite-1.0.0` and I have problems with exporting Kafka topic lag metrics.

1. Binder config is in separate context so the applications `MeterBinder` mechanism isn't using it. We can't even autowire it to build some adapter for it.
2. If you import the `KafkaBinderConfiguration` explicitly with `@Import` the `MeterBinder` is hooked up however when `bindTo` is called during application startup the `this.binder.getTopicsInUse()` returns 0 because the Kafka connections wasn't built up yet. Additionally it seems the explicit import results some beans are duplicated in the context.

**Comment by olegz** [comment]
@urgelacko just to confirm. You are trying to `@Autowire` MeterBinder. And while successful it doesn't produce the expected results. Correct?

**Comment by artembilan** [comment]
The `Micormeter` upgrade has been done as a part of the fix for the #193. Although it isn't obvious by the commit comment.

Just for info.

I think we really can't do import for the `KafkaBinderConfiguration` because the real Binder and all its goodies are definitely triggered in the separate application context as you say, @urgelacko. 
See `DefaultBinderFactory`:
```
SpringApplicationBuilder springApplicationBuilder = new SpringApplicationBuilder()
					.sources(binderType.getConfigurationClasses())
					.bannerMode(Mode.OFF)
					.logStartupInfo(false)
					.web(WebApplicationType.NONE);
```

The Spring Boot uses this approach in the `MeterRegistryPostProcessor`:
```
this.configurer = new MeterRegistryConfigurer(beansOfType(MeterBinder.class),
...
	private <T> Collection<T> beansOfType(Class<T> type) {
		return this.context.getBeansOfType(type).values();
	}
```

That's how our `KafkaBinderMetrics` isn't visible.

Not sure how to fix though, but at least this is a food for thoughts.

**Comment by artembilan** [comment]
Well, we might need to do something similar what we have in the `BindersHealthIndicatorAutoConfiguration` with the `BindersHealthIndicatorListener` and its `afterBinderContextInitialized`. So, this way we can expose target `MeterBinder` beans from the binder context to this parent context and it will be available for the `MeterRegistryPostProcessor` in Spring Boot Actuator.

I may miss something anyway and we have some hook on the core level...

//CC @olegz , @sobychacko

**Comment by artembilan** [comment]
OK.
With this test-case I got it working with some workaround. See comments below:
```
@RunWith(SpringRunner.class)
@SpringBootTest(
		webEnvironment = SpringBootTest.WebEnvironment.NONE, 
		properties = "spring.cloud.stream.bindings.input.group=" + KafkaBinderActuatorTests.TEST_CONSUMER_GROUP)
public class KafkaBinderActuatorTests {

	static final String TEST_CONSUMER_GROUP = "testGroup";

	private static final String KAFKA_BROKERS_PROPERTY = "spring.kafka.bootstrap-servers";

	@ClassRule
	public static KafkaEmbedded kafkaEmbedded = new KafkaEmbedded(1, true);

	@BeforeClass
	public static void setup() {
		System.setProperty(KAFKA_BROKERS_PROPERTY, kafkaEmbedded.getBrokersAsString());
	}

	@AfterClass
	public static void clean() {
		System.clearProperty(KAFKA_BROKERS_PROPERTY);
	}

	@Autowired
	private MeterRegistry meterRegistry;

	@Test
	public void testKafkaBinderMetricsExposed() {
		Search search = this.meterRegistry.find(
				String.format("%s.%s.%s.lag", "spring.cloud.stream.binder.kafka", TEST_CONSUMER_GROUP, Sink.INPUT));

		assertThat(search.gauge()).isNotNull();
	}

	@EnableBinding(Sink.class)
	@EnableAutoConfiguration
	public static class IntegrationKafkaConfig implements ApplicationListener<ApplicationReadyEvent> {

		@Autowired
		private MeterRegistry meterRegistry;

		private final List<MeterBinder> springCloudStreamMeterBinders = new ArrayList<>();

		@Bean
		public DefaultBinderFactory.Listener listenerForMeterBinders() {

			return (configurationName, binderContext) -> {
				springCloudStreamMeterBinders.add(binderContext.getBean(MeterBinder.class));
			};

		}

		@Override
		public void onApplicationEvent(ApplicationReadyEvent event) {
			this.springCloudStreamMeterBinders.forEach(b -> b.bindTo(this.meterRegistry));
		}

		@StreamListener(Sink.INPUT)
		public void process(String payload) {

		}

	}

}
```

The * consumer group* is very important here. Anonymous groups and topics used on the producer side are not involved in the *consumer lag* metric collection. 

Then pay attention how I expose the `KafkaBinderMetrics` to the parent application context, available for the auto-configured by the Actuator `MeterRegistry`. I implement a `DefaultBinderFactory.Listener` to get access to the target Binder application context and get an appropriate bean from there. But since it's still too early to bind it into the `MeterRegistry` I gather all the `MeterBinder` instances to the local cache and then bind them in the `ApplicationReadyEvent` phase. That is exactly when our binding are registered already.

That's how to make it working (at least somehow) with the current state.

But from here I see a different big problem in the `KafkaBinderMetrics`. Previously it has been based on the old Spring Boot `PublicMetrics` with the contract like:
```
/**
	 * Return an indication of current state through metrics.
	 * @return the public metrics
	 */
	Collection<Metric<?>> metrics();
```
The very important part was there as **current**.

The code has left the same in the `KafkaBinderMetrics`, but it is now moved to the `MeterBinder.bindTo()`. This one is called only once and when we do there `registry.gauge(String.format("%s.%s.%s.lag", METRIC_PREFIX, group, topic), lag);` we really got only the lag from the application start up phase and we don't update it at runtime whenever we might be interested to see really a current lag.

I think instead of `long lag`  we have to use the other runtime-based overloaded method:
```
  /**
     * Register a gauge that reports the value of the object.
     *
     * @param name          Name of the gauge being registered.
     * @param obj           State object used to compute a value.
     * @param valueFunction Function that produces an instantaneous gauge value from the state object.
     * @param <T>           The type of the state object from which the gauge value is extracted.
     * @return The number that was passed in so the registration can be done as part of an assignment
     * statement.
     */
    @Nullable
    public <T> T gauge(String name, T obj, ToDoubleFunction<T> valueFunction) {
```

## Conclusion

1. One issue has to go to the Spring Cloud Stream Core with the functionality to expose target binders `MeterBinder` implementations for the parent context.
2. The `KafkaBinderMetrics` must be fixed to be Micromater-"friendly" at runtime.

**Comment by urgelacko** [comment]
@olegz the `@Autowire` was just a try to hook up the lag metrics when I realized during testing it is not working.
@artembilan Thank you for the quick fix I and the detailed description. I will use it temporary until your fix is released.
