### ISSUE TITLE
Add support for topic name wildcards

### ISSUE THREAD

**Issue by a-valyaev** [spring-cloud/spring-cloud-stream-binder-kafka#339]
does consumer support topic name wildcards somehow?

i tried 
`spring.cloud.stream.bindings.input.destination=something.*`
but it fails with 'IllegalArgumentException: Topic name can only have ASCII alphanumerics, '.', '_' and '-''

thanks

**Comment by garyrussell** [comment]
The Kafka binder does not currently support it; however, the underlying Spring-Kafka project does support a Regular expression such as yours.

We can add it, but we would need a flag or something, to know that the destination is a `Pattern`. Perhaps

    spring.cloud.stream.kafka.bindings.input.destination-is-pattern=true
    spring.cloud.stream.bindings.input.destination=something.*

...then the listener container would subscribe to all topics matching that expression (and any new ones that might be added later).

**Comment by ngbalk** [comment]
Big fan of this feature, we are using this right now and it is awesome - only problem is that it causes the HealthChecks to fail in the `KafkaBinderHealthIndicator.java` because this topic name is not valid... getting the down reason:
`error: "org.apache.kafka.common.errors.InvalidTopicException: Topic '.*myDynamicTopicName' is invalid"`

This happens because we fetch partitionData from the kafka cluster for these dynamic topics.

https://github.com/apache/kafka/blob/4f25f1fb7118825384f89ed9d00c08a54870e3aa/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java#L297

**Comment by garyrussell** [comment]
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/430

**Comment by ghilainm** [comment]
@garyrussell  Hi, is there any documentation about this feature somewhere? I couldn't find any trace about it.

**Comment by garyrussell** [comment]
@ghilainm Which feature?

The PR that resolves this issue added this documentation...

**destinationIsPattern::**
When true, the destination is treated as a regular expression `Pattern` used to match topic names by the broker.
When true, topics are not provisioned, and `enableDlq` is not allowed, because the binder does not know the topic names during the provisioning phase.
Note, the time taken to detect new topics that match the pattern is controlled by the consumer property `metadata.max.age.ms`, which (at the time of writing) defaults to 300,000ms (5 minutes).
This can be configured using the `configuration` property above.
+
Default: `false`

Also see the [Spring for Apache Kafka documentation](https://docs.spring.io/spring-kafka/reference/html/_reference.html#kafka-container).

    public ContainerProperties(Pattern topicPattern)

and the KafkaConsumer javadocs:

```java
    /**
     * Subscribe to all topics matching specified pattern to get dynamically assigned partitions.
     * The pattern matching will be done periodically against topics existing at the time of check.
     * <p>
     * This is a short-hand for {@link #subscribe(Pattern, ConsumerRebalanceListener)}, which
     * uses a no-op listener. If you need the ability to seek to particular offsets, you should prefer
     * {@link #subscribe(Pattern, ConsumerRebalanceListener)}, since group rebalances will cause partition offsets
     * to be reset. You should also provide your own listener if you are doing your own offset
     * management since the listener gives you an opportunity to commit offsets before a rebalance finishes.
     *
     * @param pattern Pattern to subscribe to
     * @throws IllegalArgumentException If pattern is null
     * @throws IllegalStateException If {@code subscribe()} is called previously with topics, or assign is called
     *                               previously (without a subsequent call to {@link #unsubscribe()}), or if not
     *                               configured at-least one partition assignment strategy
     */
    @Override
    public void subscribe(Pattern pattern) {
```

**Comment by ghilainm** [comment]
@garyrussell I was searching in the spring cloud stream documentation, that's why I didn't find anything related. Thanks for the precision.
