### ISSUE TITLE
Allow state store creation when using process/transform method in DSL

### ISSUE THREAD

**Issue by orchesio** [spring-cloud/spring-cloud-stream-binder-kafka#340]
Kafka stream allows to combine low level processor API in DSL, like
input.transform(new MyTransformer() {...}).to();

To use the state, according to the official KStream document,

> In order to assign a state, the state must be created and registered beforehand:
>
>
> // create store
> StateStoreSupplier myStore = Stores.create("myTransformState")
>     .withKeys(...)
>     .withValues(...)
>     .persistent() // optional
>     .build();
>
>  // register store
>  builder.addStore(myStore);
>
> KStream outputStream = inputStream.transform(new TransformerSupplier() { ... }, >"myTransformState");

However in current binder there is no way to do that. KStream was created internally and StreamBuilder is not exposed. 
Maybe add a new annotation StateStore could help inject this into KStream creation logic so the state store can be created and added to builder?

**Comment by sobychacko** [comment]
@orchesio This model is currently not supported, but we are going to take a look at that post 2.0 (either as 2.0.1 or 2.1.0). In the meantime, contributions are welcomed!

**Comment by orchesio** [comment]
@sobychacko I'd like to contribute, but due to the unfamiliarity of spring-kafka, might need some discussion about the right approach. Should this be annotation driven or configuration file driven?
Any existing support in spring-kafka can this be built on top of? 
In my case, I need windowed state store specifically, so I was thinking about something like this:
@StreamListener("input")
@SendTo("output")
@StateStore(name="mystate", type="window", cache=disable, size=xxx, retention=xxx, "logging"=enable)

The kafka-stream-binder code can then take this and create the state store accordingly, add it to builder, then build the stream.

What do you think?

**Comment by sobychacko** [comment]
@orchesio Your general approach looks fine to me. A couple of observations and suggestions. 
I am not sure if we want to add the state store support at the spring kafka layer as SK already exposes the basic building blocks such as the builder factory beans. We are leveraging on that in the binder to create stream configs. But, @garyrussell or @artembilan may have more insights for building this support in SK itself. 
But if we are going with the premise that the `StateStore` support is added as part of the binder, then the place to add this is through this implementation in the Kafka Streams binder: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsStreamListenerSetupMethodOrchestrator.java#L150
This orchestrator creates a separate `StreamsConfig` per `StreamListener` methods in the application context. So you can inject your state store in the corresponding stream builder. You may want to study this class to implement the feature. 
But a bigger question is if we should take an annotation-driven approach vs something else. As long as we make it clear that this state store is Kafka streams specific that might be ok (As this is a new annotation that is added to the binder and needs to be supported as part of the public API). The other option is to have a property-driven approach. Both options have its pros/cons. But since you suggested the annotation approach, I suggest you start with that and then we can review the implementation. Basically, where you orchestrate the StreamListener method, you examine for the annotation and then build a state store and then inject it as part of the internal streams builder for that method. 
In any case, this is a new feature and can only be part of the 2.1.x release. But feel free to share any code you have for a review.

**Comment by orchesio** [comment]
@sobychacko PR sent.

**Comment by sobychacko** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/cf41a8a4eb88a62dbde90d7ef30918e61f4ed1b8
