### ISSUE TITLE
spring-cloud-stream-binder-kafka: duplicated "spring-cloud-stream-binder-test" in pom.xml

### ISSUE THREAD

**Issue by mayras** [spring-cloud/spring-cloud-stream-binder-kafka#381]
Duplication: 

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-test</artifactId>
			<scope>test</scope>
		</dependency>

**Comment by sabbyanandan** [comment]
Hi, @mayras. This report is incomplete. Could you update the description of how you created the project and with what versions?

**Comment by artembilan** [comment]
I think the problem is here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/pom.xml#L40
and here in the end of the same file: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/pom.xml#L63

Well, it's not a big problem though, just an IDE noise. 
One of them can be just simply removed from here on GitHub :smile:

**Comment by sabbyanandan** [comment]
Thanks, @artembilan. If you'd like to clean it up, please feel free to PR it.
