### ISSUE TITLE
Can't set useNativeEncoding as default when using transactional binder.

### ISSUE THREAD

**Issue by Woodham** [spring-cloud/spring-cloud-stream-binder-kafka#435]
When using version `Elmhurst.SR1`, I'm trying to set the default producer property for `useNativeEncoding`.

I have transactions enabled (with a `transactionIdPrefix` set), but wherever I try to set the default producer property for `useNativeEncoding` it doesn't seem to apply.

It works fine if I specify it at the specific `bindings` level.

e.g. This works:

```
spring.cloud.stream.bindings.output.producer.useNativeEncoding=true
```

But none of these seem to:

```
spring.cloud.stream.default.producer.useNativeEncoding=true
spring.cloud.stream.kafka.binder.transaction.producer.useNativeEncoding=true
```

(I've also tried several other properties with no success, but my understanding is it should be one of the above two).

**Comment by garyrussell** [comment]
When using transactions, the producer is created by the consumer (so it can begin the transaction, send the offset to the transaction and commit or rollback the transaction).

Since the consumer doesn't know which output channel(s) the application will use, the output binding's producer properties are ignored and the transactional producer properties are configured at the binding level.

See [the documentation](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/index.html#_kafka_binder_properties); specifically:

`spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix`

Enables transactions in the binder. See `transaction.id` in the Kafka documentation and Transactions in the spring-kafka documentation. When transactions are enabled, individual producer properties are ignored and all producers use the `spring.cloud.stream.kafka.binder.transaction.producer.*` properties.

Default null (no transactions)

`spring.cloud.stream.kafka.binder.transaction.producer.*`

Global producer properties for producers in a transactional binder. See `spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix` and Kafka Producer Properties and the general producer properties supported by all binders.

Default: See individual producer properties.

**Comment by garyrussell** [comment]
Sorry, I misread your question; this should work...

    spring.cloud.stream.kafka.binder.transaction.producer.useNativeEncoding=true

**Comment by garyrussell** [comment]
Sorry, I misread your question; this should work...

    spring.cloud.stream.kafka.binder.transaction.producer.useNativeEncoding=true

...so it's a bug; the abstract binder where this property is examined knows nothing about Kafka transactions and that the binding producer properties aren't used.

Neither of these should

    spring.cloud.stream.bindings.output.producer.useNativeEncoding=true
    spring.cloud.stream.default.producer.useNativeEncoding=true

But there's probably an argument that the second one should.

**Comment by Woodham** [comment]
Sorry yes I meant to say I'd tried `spring.cloud.stream.kafka.binder.transaction.producer.useNativeEncoding=true`
I just forgot to note it down in the ticket (I tried many combinations to make sure I wasn't doing something stupid :) )

Thanks for the confirmation - for now I'll just specify it on each binding individually.
