### ISSUE TITLE
Unable to turn off kafka health indicator

### ISSUE THREAD

**Issue by voncuver** [spring-cloud/spring-cloud-stream-binder-kafka#454]
Currently Health indicator is created on:
`@ConditionalOnClass(name="org.springframework.boot.actuate.health.HealthIndicator")`

And we can not simple disable it anyhow,

Can you add standard actuator mechanism?

`@ConditionalOnEnabledHealthIndicator("kafka")
@AutoConfigureBefore(HealthIndicatorAutoConfiguration.class)`

Then we could disable healthIndicator in actutor standard way by:
`managment.health.kafka.enabled=true`

**Comment by sobychacko** [comment]
@voncuver [This class](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindersHealthIndicatorAutoConfiguration.java) from core is responsible for providing the infrastructure necessary for the registration of binder specific health indicators. Ideally speaking, we can disable the kafka binder specific `HealthIndicator` by providing the boot property `managment.health.binders.enabled=fase`. However, there is a bug that still registers `KafkaBinderHealthIndicatorConfiguration`. 

Instead of doing this:

```
@Configuration
@ConditionalOnClass(name="org.springframework.boot.actuate.health.HealthIndicator")
class KafkaBinderHealthIndicatorConfiguration
```

we need to do something like this:

```
@Configuration
@ConditionalOnBean(name = "bindersHealthIndicator") //this is the bean that the core registers, if its //missing since the user disabled health check, we won't load this configuration
class KafkaBinderHealthIndicatorConfiguration
```
Please let us know if that meets your requirements. If so, we can address this bug.

**Comment by sobychacko** [comment]
@voncuver There is a PR in flight that addresses disabling the binder specific health indicator. Once that is merged, you can use `management.health.binders.enabled=false` to disable health check. In the event an app uses multi binders, then this property has to be given as part of the corresponding binder environment properties in the application's configuration properties (or yaml).
