### ISSUE TITLE
Microservice cannot be up when kafka is down

### ISSUE THREAD

**Issue by Tal24** [spring-cloud/spring-cloud-stream-binder-kafka#476]
We use Spring boot and our MS tries to connect to kafka and can't be up until kafka is up, late binding is support as written here:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12
So what works for us is the **re-try**, the service keeps trying to connect to kafka every 30 seconds as implemented in this property - spring.cloud.stream.bindingRetryInterval .
But we want the service to be up no matter if kafka is down or not, we do want late binding, we want the service to try to connect to kafka every 30 seconds but we want it to be under the hood and meanwhile We want the service to be up so we can make REST calls to the service.

Is there a way to implement this?

**Comment by garyrussell** [comment]
When attempting to provision the topic, the provisioner blocks for 30 seconds waiting for the result (currently not configurable).

Since the admin is running in an autoclosable `try` block; we then try to `close()` the admin - which waits for another 90 seconds - a total of 2 minutes, which is the default admin request timeout.

So, the application should start after 2 minutes.

We should change the try to use a finally and only close the admin client if it's actually open (or use a shorter close timeout).

However, you can reduce the 2 minutes as follows...

    spring.kafka.admin.properties.request.timeout.ms=5000

**Comment by Tal24** [comment]
spring.kafka.admin.properties.request.timeout.ms=5000, that works great. thanks.
