### ISSUE TITLE
Kafka partitioning configuration and skipped messages

### ISSUE THREAD

**Issue by benjvoigt** [spring-cloud/spring-cloud-stream-binder-kafka#542]
Spring version: `org.springframework.cloud:spring-cloud-dependencies:Finchley.RELEASE`

I am investigating a problem in our microservice applications in which rarely messages are not delivered to the consumers. We're using kafka and I do have some questions regarding partitioning since this might cause the problem but tbh I have no idea why it happens, so this is the only thing I can imagine right now. There is also no lag for the offset in the affected consumer group, so from the broker perspective everything looks okay but the message was not processed by the event handler nor received by the consumer (i assumed it would throw an error if no stream listener is registered for the message but logs are empty).

These are the important bits of the application configuration:

```
spring.cloud.stream.bindings.output.destination=${spring.application.name}
spring.cloud.stream.kafka.bindings.output.producer.sync=true
spring.cloud.stream.default.group=${spring.application.name}
spring.cloud.stream.default.producer.partitionCount=9
spring.cloud.stream.default.producer.partitionKeyExpression=headers.entityId
spring.cloud.stream.kafka.binder.autoAddPartitions=true
spring.cloud.stream.kafka.binder.autoCreateTopics=false
```
In addition, `auto.create.topics.enable` is set to `false` for the broker.

According to the binder docs (http://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RELEASE/single/spring-cloud-stream-binder-kafka.html#_partitioning_with_the_kafka_binder) I am missing the following property right now, but the question is, can this be the cause?
`spring.cloud.stream.bindings.output.producer.partitioned=true`
Why exactly should this property be set? The topic is created with the specified number of partitions even with `partitioned=false`. What are the side effects having this set to false?

Furthermore the general docs (http://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.1.0.RELEASE/single/spring-cloud-stream.html#_consumer_properties) mention a similar property for the consumer but it's not clear why or if this should be set? 

`spring.cloud.stream.bindings.<channelName>.consumer.partitioned`
_Whether the consumer receives data from a partitioned producer._

**Comment by garyrussell** [comment]
That documentation is out of date (producer side); it is a derived property.

```java
	public boolean isPartitioned() {
		return this.partitionKeyExpression != null
				|| this.partitionKeyExtractorName != null
				|| this.partitionKeyExtractorClass != null;
	}
```

It is only used if you are calculating the key with an expression or extractor.

On the consumer side, it is only used by binders for technologies that do not support partitioning natively. This does not apply to Kafka.

**Comment by benjvoigt** [comment]
> That documentation is out of date (producer side); it is a derived property.

Are you sure? Since the kafka binder itself does not derive this property as far as i can see:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/search?q=partitioned&unscoped_q=partitioned

**Comment by garyrussell** [comment]
Yes I am sure; the combined properties delegate to the code I showed; it is only true if you configure binding-level partitioning and only then do we set a partition in the record.

When NOT using binder-partitioning, Kafka decides which partition gets a message, based on its `partitioner.class` property. By default, you get a `DefaultPartitioner`...

```java
/**
 * The default partitioning strategy:
 * <ul>
 * <li>If a partition is specified in the record, use it
 * <li>If no partition is specified but a key is present choose a partition based on a hash of the key
 * <li>If no partition or key is present choose a partition in a round-robin fashion
 */
public class DefaultPartitioner implements Partitioner {
```

**Comment by benjvoigt** [comment]
Okay I understand. Now, I am also quiet sure that the partitioning works as expected. Maybe the skipped messages are due to how the offsets are committed but I'll need to investigate further and get back as soon as I know more.

Just one more question ahead: I assume the message delivery guarantee is at-least-once, right? Since `enable.auto.commit` is set to `false` for the kafka client, the binder cares about committing offsets properly. So if a batch of messages is received, they're dispatched to all available stream listeners in parallel and if one fails the entire batch fails aka no offset is committed...? On the next _run_ the same batch is received basically. This way no messages would ever be skipped but maybe process multiple times. Otherwise, if the (higher) offset for one of the parallel running stream listener would be committed even tho another one with a lower offset fails, then the failed one would be skipped forever.

Still these answers would not explain why the messages are never received (aka no logs) in the first place.

**Comment by garyrussell** [comment]
>So if a batch of messages is received, they're dispatched to all available stream listeners in parallel

No; it doesn't work that way, unless you increase the `consumer.concurrency` property; in which case you that number of threads and the partitions are distributed amongst them. When there's only one consumer, all partitions are delivered, one-by-one, on one thread.

The ack behavior depends on the binder properties.

- `spring.cloud.stream.kafka.binding.foo.auto-commit-offset` 

When true (default), the listener container commits the offsets after the whole batch is processed; when false, the application has the responsibility of acking the record(s) using the `KafkaHeaders.ACKNOWLEDGMENT` message header.

- `spring.cloud.stream.kafka.binding.foo.ack-each-record` (default false)

When true, and `auto-commit-offset` is `true` commit the offset after each record is processed instead of after the entire batch is processed. Uses more bandwidth but reduces the possibility of duplicates.

**Comment by benjvoigt** [comment]
Okay, so let's say a batch of 500 messages (kafka default) is fetched into memory. Now each message is dispatched to the matching stream listener one by one. If the 123rd message fails does the binder stop processing the remaining messages and fails early without committing any offset? I still assume that the same 500 messages will be fetched into memory afterwards.

**Comment by garyrussell** [comment]
It depends on the retry and DLQ configuration and, finally, the `ErrorHandler` in the binder's listener container.

(The binder doesn't currently provide a mechanism to customize the error handler - it should - I will open an issue for that).

When retry is not configured, or retries are exhausted, and `dlqEnabled=true`, the record is considered "consumed" after is sent to the dead letter topic (the container knows nothing about the failure so it sees it as a successful delivery).

When `dlqEnabled=false` the (final) exception is thrown to the container, which invokes its `ErrorHandler`.

The default error handler is a `LoggingErrorHandler` which simply logs the error (this is not currently changeable, in the binder). Whether or not the offset is committed depends on the consumer `auto-commit-on-error` property (default) false. 

The container then calls the listener with the remaining records (from 124 in your example).

Of course, the `auto-commit-on-error` property is pretty useless because the next record's offset will soon be committed anyway.

Now, if the binder had a configurable error handler, you could wire in a `SeekToCurrentErrorHandler`, in which case, before it is called, any pending commits are performed (if `ackEachRecord=false`) and the failed record and all the remaining records are passed to the error handler. In effect discarding the rest of the batch. However, that error handler performs seeks on the `Consumer` so that all these records will be redelivered on the next poll. It also has a retry mechanism and "gives up" on a record that keeps failing by calling some `recoverer` which needs to dispose of the message in some way (the spring-kafka provides a `DeadLetterPublishingReoverer` that provides similar functionality to the binder's DLQ mechanism for users of the project that are not using Spring Cloud Stream). The default recoverer just logs the error but you can wire in whatever recovery mechanism you want.
