### ISSUE TITLE
Boot's Actuator Health is down with Kafka and KStreams binders in the classpath

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#552]
As a user, I'm attempting to run a Kstreams app (Fishtown.SR1) in Kubernetes, but the health-checks are failing for some reason and because of that the liveness probes fail - thus leading to container restart over and over.

This was observed when both Kafka and KStreams binders are in the classpath (see: [sample](https://github.com/sabbyanandan/eda/tree/master/userconsumer)) - it used to work on Elmhurst and earlier Fishtown milestones); with Kafka binder removed from the app, the health checks return as `UP`.

Let's isolate as to what causes the collision to return the status as `DOWN`.

**Comment by sobychacko** [comment]
@sabbyanandan I don't think this a bug per se. This was introduced by this [change/PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/496). Earlier there was an issue in the regular Kafka binder when there were no topics (destinations) registered by the binder, then even in situations when Kafka server was `DOWN`, we erroneously used to report that the server was `UP`. In order to fix this, in the aforementioned PR, we check first if the binder has any registered destinations. Only then, the health check continues, otherwise, we assume that the binder (provisioner) was unable to connect to Kafka, thus marking the server as `DOWN`. In this particular case that triggered this issue, there were both binders present but only one binder was actually being used in the application. If the reguarl binder was actually used in the application to bind to some destinations, then the health checks would have worked. By only providing it in the classpath, but not using in the application, the binder didn't register any destinations thus failing the healthcheck.

**Comment by sabbyanandan** [comment]
Thanks, @sobychacko! That makes sense, and I get why. I updated my sample to include just the KStreams binder - all is well. 

We will document the behavior via spring-cloud/spring-cloud-stream#1620.

**Comment by tdanylchuk** [comment]
Behavior seems to be OK, but unfortunately not for all cases:

Let's assume we have both KStream binder and plain kafka binder.

But service don't use by default kafka binder, but only KStream binder, means kafka binder enabled only if user want to enable it, which makes it optional, so dependency of kafka binder should be bundled with the service jar.

In this case I expect Binder healthcheck just not to go DOWN, if it does not have available bindings, since currently user just does not want to enable them.

So two options which are currently available are not OK for this case:
- disable binder healthchecks (means KStream healthcheck also should be disabled, which is not okay)
- remove kafka binder dependency (means user will not have option to include some features in future backed by kafka binder)

Possible solutions:
- binders should be disabled by name
- do not make kafka binder ```DOWN``` if bindings list is empty

**Comment by sobychacko** [comment]
@tdanylchuk Anything other than `UP` in binder components will be reported with an overall status of `DOWN` by the health actuator endpoint. So, even if we send an `UNKNOWN` status, I am afraid, you will still see the `DOWN` status. With that said, here is something that you can do if you still want to include both binders, but disable one. Let's say you want to disable the kafka binder health check. You can create custom environment for the binders as below.
```
spring.cloud.stream.binders.kafka1.type = kafka
spring.cloud.stream.binders.kafka1.environment.management.health.binders.enabled = false

spring.cloud.stream.binders.kstream1.type = kstream

spring.cloud.stream.bindings.input1.binder = kafka1
spring.cloud.stream.bindings.input2.binder = kstream1
```
In this case, the health check is disabled for Kafka binder and it is enabled by default for the kafka streams binder.  See if this solution works for you.

**Comment by tdanylchuk** [comment]
well health indicator should not go down in case if one is in ```UNKNOWN``` state, example:
```
{
    "status": "UP",
    "details": {
        "custom": {
            "status": "UNKNOWN"
        },
        "refreshScope": {
            "status": "UP"
        }
    }
}
```

and settings these variables to env:
```
spring.cloud.stream.binders.kstream.environment.management.health.binders.enabled=true
spring.cloud.stream.binders.kstream.type=kstream

spring.cloud.stream.binders.kafka1.type=kafka
spring.cloud.stream.binders.kafka1.environment.management.health.binders.enabled=false
```

leads to:
```
"binders":{ 
   "status":"UNKNOWN",
   "details":{ 
      "kafka1":{ 
         "status":"UNKNOWN"
      },
      "kstream":{ 
         "status":"UNKNOWN"
      }
   }
}
```

Anyways even if this will help, after enabling one of the binding by user, the fact of enabling it's healthcheck can be forgotten...

**Comment by sobychacko** [comment]
@tdanylchuk Thanks for the feedback. We should try to improve on that if it is confusing.

**Comment by sobychacko** [comment]
@tdanylchuk What do you think about this output?

```
{
  "status": "UP",
  "components": {
    "binders": {
      "status": "UP",
      "components": {
        "kstream": {
          "status": "UP",
          "details": {
            ...
            }
          }
        },
        "kafka": {
          "status": "UNKNOWN",
          "details": {
            "No bindings found": "Kafka binder may not be bound to destinations on the broker"
          }
        },
```
