### ISSUE TITLE
Allow for custom StateStoreSupplier

### ISSUE THREAD

**Issue by rnbWarden** [spring-cloud/spring-cloud-stream-binder-kafka#627]
Are there any plans to expand the available StateStores and ideally allow for custom StateStores to be used? The implementation added as part of #340 makes static calls to `org.apache.kafka.streams.state.Stores` for a `StoreSupplier`. This works great until you want to use one of the non-default StateStores (ex: inMemoryKeyValueStore) or implement a new one. I assume I'll need to tap into `StreamsBuilderFactoryBean` but this doesn't appear to be very straightforward. Am I missing an obvious hook / extension point?

**Comment by sobychacko** [comment]
Hi @rnbWarden This problem is somewhat orthogonal to [this issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/556), but the solution for both is identical. As described in [this comment ](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/556#issuecomment-471774775), the solution is to use `StreamsBuilderFactoryBeanCustomizer` from Spring for Apache Kafka. However, that feature is only available in the newer versions of Spring Kafka and not the one that is used by the binder currently. In the next version of Spring Cloud Stream (2.3.x), we will pick up the new version of Spring Kafka and you can use that solution.
In the meantime, here is a workaround you can follow. The basic idea is to access the `StreamsBuilderFactoryBean` bean from your `StreamListener` method and directly inject the custom state stores there. Here is a rough code snippet for that:

```
@Autowired
ConfigurableApplicationContext context;

@StreamListener
@SendTo("output")
public KStream<?, ?> process(
	@Input("input") KStream<?, ?> input) throws Exception{

	context.getBean(StreamsBuilderFactoryBean.class).getObject().addStateStore(new 
                      StoreBuilder() {
...
...
	});
//Your processing code goes here
}
```
Please ensure that you access the `StreamsBuilderFactoryBean` from the `StreamListener` method as the factory bean is guaranteed to be created by the time this method is processsed. 

If you have multiple `StreamListener` methods in your application you need to access the `StreamsBuilderFactoryBean` using the following pattern. 
`context.getBean(beanNameOfStreamBuilderFactory)` where `beanNameOfStreamBuilderFactory` is defined as `&stream-builder-` followed by `Foo-process` where `Foo` is the simple class name where `StreamListener` is defined and `process` is the actual `StreamListener` method name. 

If this workaround helps, please let us know. We will use this issue to document this workaround in the reference docs.

**Comment by rnbWarden** [comment]
Thanks @sobychacko. This approach worked great. I've verified `context.getBean(StreamsBuilderFactoryBean.class);` works. I'll validate the multi-stream approach as well and update this ticket with my findings.

**Comment by rnbWarden** [comment]
The multi-stream approach worked almost as you described but with a slight modification. I did not need the simple class name in the string when pulling the bean from the context. This worked for me...

`(StreamsBuilderFactoryBean) context.getBean("&stream-builder-processFooNotification")`

... which follows this line in `KafkaStreamsStreamListenerSetupMethodOrchestrator`

`StreamsBuilderFactoryBean streamsBuilderX = applicationContext.getBean("&stream-builder-" + method.getName(), StreamsBuilderFactoryBean.class);`
