### ISSUE TITLE
stream kafka support apache plusar ?

### ISSUE THREAD

**Issue by imbaq123** [spring-cloud/spring-cloud-stream-binder-kafka#639]
stream kafka whether to support apache plusar ?

**Comment by sobychacko** [comment]
@imbaq123 Can you please provide more context? It's not exactly clear what you are asking. There is no adapter or anything like that currently available (or in the roadmap) in the Kafka binder for Apache Pulsar.

**Comment by sabbyanandan** [comment]
Yahoo! Japan is using an in-house Spring Cloud Stream binder implementation for Pulsar (see [here](https://www.slideshare.net/techblogyahoo/spring-cloud-stream-jjugccc-ccca4)). We are trying to have them open-source it, though. Otherwise, we do not have any plans to add a Pulsar binder right now. Kafka Streams like functionality for Pulsar is entirely a different topic, too, and that's not in the scope of this project.

**Comment by karode** [comment]
@sabbyanandan Any update on getting the binder implementation for Pulsar ?
