### ISSUE TITLE
Non-native serialization/deserialization for KTable operations

### ISSUE THREAD

**Issue by msmsimondean** [spring-cloud/spring-cloud-stream-binder-kafka#659]
At the moment, KTable operations like `aggregate` do not seem to use Spring serialisation/deserialisation.  Instead you get errors from the native Serdes saying types cannot be converted.

**Comment by msmsimondean** [comment]
See https://github.com/msmsimondean/spring-cloud-stream-kafka-streams/blob/master/src/main/java/com/example/analytics/AnalyticsApplication.java#L113 for an example.

**Comment by msmsimondean** [comment]
@sobychacko is this a duplicate of https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/354?

**Comment by sabbyanandan** [comment]
Hi, @msmsimondean. Thanks for the report. Can you describe the use-case(s) as to why you would need a non-native SerDe support? Typically, we see folks defaulting to the ones provided by Kakfa/KStreams, so I'm curious.

**Comment by msmsimondean** [comment]
I'm not using anything exotic, JSON serialisation.  I found the Spring Cloud Kafka Stream docs a little confusing, where they mention Spring serialisation for inputs and outputs but don't mention that intermediate steps need native SerDe.  I've struggled to get Kafka's native Json SerDe to work.  Would it be possible to add an example to the documentation?

**Comment by sobychacko** [comment]
All types in Kafka Streams binder (`KStream`, `KTable` and `GlobalKTable`) use the native Serdes mechanism by default (i.e. serialization done natively in Kafka). If the type that you are dealing with is `KStream`, then there is an option for using Spring's message converters (by setting native decoding/encoding to `false`). We haven't seen many use cases in which it is a pressing need to provide the same option for the table types. Therefore, closing this issue. Feel free to reopen if anyone feels otherwise and provide more details of the use case. Thank you!
