### ISSUE TITLE
JsonSerializer/JsonDeserializer appends a new header (header keys are not unique, and duplicates are allowed).

### ISSUE THREAD

**Issue by arslanakhtar61** [spring-cloud/spring-cloud-stream-binder-kafka#685]
This is a reference to the [answer](https://stackoverflow.com/a/56595015/6434650) on StackOverflow.

KStream-KStream inner join throws java.lang.ClassCastException when using JsonSerializer/JsonDeserializer because the types of Kafka messages key/value are encoded in the record headers, but the headers are never cleaned up. Each time the type changes, just a new header is appended (header keys are not unique, and duplicates are allowed).

**Comment by garyrussell** [comment]
Hmmm - the type headers are now removed by the deserializer, by default, [since Spring for Apache Kafka version 2.2](https://github.com/spring-projects/spring-kafka/pull/797).

You are using 2.2.6 so I don't know how this could happen.

Investigating...

**Comment by garyrussell** [comment]
Well, since you provide concrete type information to the deserializers, you don't need type information in the headers. So I disabled it but we still get the same class cast exception.

So, there's something else going on...

`Producers`...

	props.put(JsonSerializer.ADD_TYPE_INFO_HEADERS, false);

Serdes:

```java
public class PersonKeySerde extends Serdes.WrapperSerde<PersonKey> {

	public PersonKeySerde() {
		super(keySerializer(), new JsonDeserializer<>(PersonKey.class));
	}

	private static JsonSerializer<PersonKey> keySerializer() {
		JsonSerializer<PersonKey> ser = new JsonSerializer<>();
		ser.setAddTypeInfo(false);
		return ser;
	}

}

public class PersonSerde extends Serdes.WrapperSerde<Person> {

	public PersonSerde() {
		super(valueSerializer(), new JsonDeserializer<>(Person.class));
	}

	private static JsonSerializer<Person> valueSerializer() {
		JsonSerializer<Person> ser = new JsonSerializer<>();
		ser.setAddTypeInfo(false);
		return ser;
	}

}

public final class SchoolKeySerde extends Serdes.WrapperSerde<SchoolKey> {

	public SchoolKeySerde() {
		super(keySerializer(), new JsonDeserializer<>(SchoolKey.class));
	}

	private static JsonSerializer<SchoolKey> keySerializer() {
		JsonSerializer<SchoolKey> ser = new JsonSerializer<>();
		ser.setAddTypeInfo(false);
		return ser;
	}
}

public class SchoolSerde extends Serdes.WrapperSerde<School> {

	public SchoolSerde() {
		super(valueSerializer(), new JsonDeserializer<>(School.class));
	}

	private static JsonSerializer<School> valueSerializer() {
		JsonSerializer<School> ser = new JsonSerializer<>();
		ser.setAddTypeInfo(false);
		return ser;
	}

}
```

```
java.lang.ClassCastException: com.sample.kafkastreamjoin.model.School cannot be cast to com.sample.kafkastreamjoin.model.Person
	at org.apache.kafka.streams.kstream.internals.AbstractStream.lambda$reverseJoiner$0(AbstractStream.java:98) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.kstream.internals.KStreamKStreamJoin$KStreamKStreamJoinProcessor.process(KStreamKStreamJoin.java:94) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:183) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:162) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:122) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.kstream.internals.KStreamJoinWindow$KStreamJoinWindowProcessor.process(KStreamJoinWindow.java:55) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:183) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:162) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:122) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:366) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:420) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:889) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:804) ~[kafka-streams-2.2.1.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:773) ~[kafka-streams-2.2.1.jar:na]
```

Since I also confirmed that the deserializer was removing the headers, I don't think this problem has anything to do with the headers.
```

**Comment by mjsax** [comment]
Why `2.2.6`? I only see `2.1.5`(https://github.com/arslanakhtar61/kafkaStreamJoin/blob/master/pom.xml#L8) and `2.1.0` (https://github.com/arslanakhtar61/kafkaStreamJoin/blob/master/pom.xml#L128) in the pom?

Let me try to disable headers (as you proposed `props.put(JsonSerializer.ADD_TYPE_INFO_HEADERS, false);`) and investigate...

**Comment by garyrussell** [comment]
2.1.5 is the Spring Boot version; it depends on Spring-Kafka 2.2.6.

I am not very familiar with KStreams, but in the debugger, I see it trying to call his `(school, person) -> ` lambda with

    value1 = School{address='Sector F/8'}
    value2 = School{address='null'}

i.e. 2 schools.

**Comment by mjsax** [comment]
Setting the config globally to disable the headers is not enough. The application code creates some `Serdes` manually:

 - https://github.com/arslanakhtar61/kafkaStreamJoin/blob/master/src/main/java/com/sample/kafkastreamjoin/KafkaStreamJoinApplication.java#L35
 - https://github.com/arslanakhtar61/kafkaStreamJoin/blob/master/src/main/java/com/sample/kafkastreamjoin/KafkaStreamJoinApplication.java#L48

Those `Serdes` still write the headers because they are not configured. It's the users responsibility to call `configure()` before the objects are passed, to disable type information in the headers.

**Comment by garyrussell** [comment]
Right - I showed in my [comment above](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/685#issuecomment-504463248) how I disabled it there too.

**Comment by garyrussell** [comment]
BTW, it's working fine for me now, I must have had some cruft left behind. I deleted all the working topics, changed the `application.id`, and now...

```
school_app2= School{address='Sector F/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector G/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector H/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector J/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector C/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector Z/8'}, person_app2= Person{age=12.0}
school_app2= School{address='Sector S/8'}, person_app2= Person{age=12.0}
```

I still need to investigate why the header removal didn't help in this scenario - I definitely saw the headers being removed in the debugger.

**Comment by mjsax** [comment]
Nevertheless, thinking about how type information is added to headers, it still seems not perfect to blindly append a new header on write without checking existing headers. An existing header (with the corresponding key) should be removed, or maybe fail with an exception if a duplicate header is detected. It's kinda error prone the way it's implemented now, because the consumer also blindly picks the first header with corresponding key (not checking for duplicates).

**Comment by garyrussell** [comment]
Agreed; what's confusing me right now is the first call to a serializer or deserializer is `serialize` (with an existing header). I don't see how we can get there without calling a deserializer first.

The data is a `School` so something deserialized it 😕

**Comment by garyrussell** [comment]
Never mind; my breakpoint was in a different version :(

Still investigating...

**Comment by garyrussell** [comment]
Seems like streams retains an old copy of the headers in some circumstances.

Moved to https://github.com/spring-projects/spring-kafka/issues/1137 .

**Comment by mjsax** [comment]
> Seems like streams retains an old copy of the headers in some circumstances.

Yes, all input record headers are preserved since Kafka 2.0 (cf. https://cwiki.apache.org/confluence/display/KAFKA/KIP-244%3A+Add+Record+Header+support+to+Kafka+Streams+Processor+API) and forwarded to all output records that are a result of processing a single input record.

It was a problem in older releases that Kafka Streams stripped all headers on write. Users often want to preserve header information, what was decided to be the new default, making for example simple `stream->filter()->output` application behavior straightforward. User can still modify (and/or remove) headers manually as part of their business logic.

Thanks for looking into this issue and the quick turn-around time to fix it.

**Comment by garyrussell** [comment]
@mjsax Thanks for your analysis on Stack Overflow. There were 2 problems - adding rather than replacing the header(s) and iterating forward instead of using `lastHeader()`. We're now doing both.
