### ISSUE TITLE
Add hooks to the stream binder to allow custom processors/transformers to be applied

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-kafka#699]
As a user, I would like some mechanism whereby I can add custom processors/transformers to the stream topology without doing it in my business logic topology.

A concrete example would be to add sleuth instrumentation; see https://github.com/spring-cloud/spring-cloud-sleuth/issues/1363#issuecomment-507998812.

**Comment by sobychacko** [comment]
Leaving this issue open and moving to the backlog. Basically, although the instrumentation is possible by explicitly wrapping transformers/processors in `KafkaStreamsTracing`, it is still desirable to have[ implicit instrumentation](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1363#issuecomment-525596420) behind the scenes if slueth classes are on the classpath. For the binder, it turns out to be a non-trivial effort as it needs to scan the application for any transformer/processors and then proxy those to a wrapper where we apply corresponding counter parts from `KafkaStreamsTracing`. For the time being, the applications have to follow the explicit mechanism explainer [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/699#issuecomment-525458632). We will consider making it implicit if there is more user requests for this feature.

**Comment by magnuskvalheim** [comment]
Implicit instrumentation get a 👍  from me.
We are using the KafkaStreamsTracing. We are thankful - it's working, but the usage is a little awkward.

@sobychacko - I haven't started digging into the details, but do you have an idea of how you would go about it?
From your last comment I see that one approach would be to scan for transformers and processors.

Guess that would be a little better - however, ideally, I'd like to see it instrumented with the streams api directly (without creating spring beans). Do you think that's possible?

**Comment by codependent** [comment]
Explicit instrumentation worked for me as well, with some changes though: the `brave.kafka.streams.KafkaStreamsTracing` API has changed from the one used in the previous example. The current one requires a TransformerSupplier instead of a Transformer:

Not valid anymore:

```
return kafkaStreamsTracing.transformer(
		"transformer-1",
		new Transformer<String, String, KeyValue<String, String>>() {
			ProcessorContext context;
```

```
public final class KafkaStreamsTracing {
...
    public <K, V, R> TransformerSupplier<K, V, R> transformer(String spanName,
        TransformerSupplier<K, V, R> transformerSupplier) 
```

Despide this nice workaround it would be ideal to have an implicit way to have this instrumentation.

**Comment by sobychacko** [comment]
@magnuskvalheim @codependent I took a look at this again. It remains non-trivial to add this type of functionality to the binder from the options I explored. What I am trying to understand are the downsides of adding the wrapper from the application code itself. What is wrong with the code below apart from the fact that you need to inject `KafkaStreamsTracing` directly and call`transformer` on that instead of providing the transformer directly? 

```
@Bean
public Function<KStream<String, String>, KStream<String, String>> foo(KafkaStreamsTracing kafkaStreamsTracing) {
	return input -> input.transform(kafkaStreamsTracing.transformer(
			"transformer-1",
			() -> new Transformer<String, String, KeyValue<String, String>>() {
				ProcessorContext context;

				@Override
				public void init(ProcessorContext context) {
					this.context = context;
				}

				@Override
				public KeyValue<String, String> transform(String key, String value) {
					LOG.info("Headers: " + this.context.headers());
					LOG.info("K/V:" + key + "/" + value);
					return KeyValue.pair(key, value);
				}

				@Override
				public void close() {}
				}));
}
```

 It boils down to the fact that the binder cannot possibly know all the locations or methods that the application wants to trace, it simply in the applications'  business logic to directly address that using the `KafkaStreamsTracing` injection. 

That being said, if you have some specific ideas as to how we can implement this, we can certainly explore those. Please let us know if you find better ways to support this.

**Comment by codependent** [comment]
Hi @sobychacko I see your point and understand that this is a tricky one. It would be great to have that instrumentation transparently, but anyway, for me the workaround of doing it manually is fine.

**Comment by magnuskvalheim** [comment]
Yes - it's a workable solution. I too understand that it may not be
feasible to further improve it currently.

A question - with your knowledge on internals.
Do you see an opportunity to request for better integration points/handles
provided by kafka streams api?
Maybe that could enable for a better solution - in the long term?

/magnus

Den man. 22. feb. 2021 kl. 11.54 skrev Jose A. Iñigo <
notifications@github.com>:

**Comment by sobychacko** [comment]
@magnuskvalheim What kind of integration points are you referring to?

**Comment by sobychacko** [comment]
@codependent @magnuskvalheim When spring-cloud-sleuth is in the classpath, the client supplier from `KafkaStreamsTracing` in brave instrumentation is set on the `StreamsBuilderFactoryBean` created by the binder. The factory bean passed [here](https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/messaging/BraveKafkaStreamsAutoConfiguration.java#L106) when using Spring Cloud Stream is the one created by Kafka Streams binder. Therefore, you get all the trace headers passed downstream through your topology. For diagnostic scenarios like the ones which are provided above, i.e. explicitly calling `transformer` on `KafkaStreamsTracing` unfortunately still remains the responsibility of the application.

**Comment by sabbyanandan** [comment]
cc:/ @tzolov (for: SCDF/TO/Wavefront)

**Comment by sobychacko** [comment]
Closing this issue. Please feel free to reopen if there is a compelling reason not to use the workaround mentioned above (or another viable solution is found).
