### ISSUE TITLE
Don't reuse consumer group from `spring.kafka.consumer`

### ISSUE THREAD

**Issue by pmahony893** [spring-cloud/spring-cloud-stream-binder-kafka#832]
We are working on applications that use Kafka both for application logic (not using Spring Cloud Stream), and also as the binder for Spring Cloud Bus. We use Config Server to broadcast configuration changes to our application instances, over Spring Cloud Bus.

We have `spring.kafka.consumer.group-id` set for our application logic. However, Spring Cloud Stream is attempting to re-use that when binding to the `springCloudBus` topic. This means that all of our refresh events are only processed by one application instance - not ideal! 

We know (after a day of searching through code and documentation) that we can override this using the `spring.cloud.stream.kafka.binder.consumerProperties.group.id` property, however this is very unintuitive. It should at least be clearly documented - I'm surprised this is an issue no-one has come across before!

Also, the code surrounding this, in `KafkaMessageChannelBinder.createConsumerEndpoint` seems to get very confused about what the consumer group is; it generates one of the form `anonymous.<guid>`, but this is overridden in the `createKafkaConsumerFactory` if `spring.kafka.consumer.group-id` is set.

Please advise if we're missing something!

**Comment by sobychacko** [comment]
@pmahony893 In Spring Cloud Stream, a consumer group is a first-class concept in consumer applications. This can be represented by the configuration property `spring.cloud.stream.bindings.<input-binding-name>.group` or `spring.cloud.stream.default.group`. 

Following is the order in which binder checks for group id. 
1. When the binder is tasked with creating a consumer binding, it is provided with the aforementioned property if it is set. 
2. If this property is not set, then the binder assumes that the consumer is anonymous (effectively creating a single-member consumer group).
3. Then later on in the `createKafkaConsumerFactory`, it merges any consumer properties set by boot auto-configuration, binder level properties, etc. However, in the case of `group.id`, the binder will filter that information out, so that the group represented through the above properties still take effect. The property you mentioned - `spring.cloud.stream.kafka.binder.consumerProperties.group.id` also gets filtered out so that the stream managed group property takes effect. 

Please let us know if you are still having trouble with this.

**Comment by pmahony893** [comment]
@sobychacko Thanks for responding so quickly!

The issue we're having is that when the consumer properties get merged in step 3, it's not filtering out the `group.id`, as it should. This is with version 2.1.2-RELEASE - has something changed since then?

**Comment by sobychacko** [comment]
@pmahony893 The filtering of the `group.id` I mentioned in step 3 above wasn't added in `2.1.x`. Can you upgrade to the latest `2.2.x` or `3.x`?

**Comment by pmahony893** [comment]
@sobychacko Ok thanks for confirming that! We'll look into upgrading.
