### ISSUE TITLE
Using transaction-id-prefix removes deliveryAttempt field in Kafka Header

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#858]
Hello,

I am using Spring Cloud Stream Binder Kafka for exactly-once semantics.

I only supply configs through application.yml and I don't override any beans related to Spring Cloud Stream or Spring Kafka currently.

I was looking at the reference and found config for transactional producer :
spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix.

However, when that option is set to some value (let's say "test-tx-id-"), I noticed that on the Consumer side (@StreamListener), there is no deliveryAttempt field in Kafka Header. Consumer side would look as follows.

```
@StreamListner(SourceBinding.INPUT)
public void listen(Message<String> message) {
    ... do something
}
```

deliveryAttempt has been very helpful to me in terms of debugging and finding out if a received message was retried or not. 

So my questions would be:
1. Is this a desired behavior or a bug? I am not sure if this (transaction-id-prefix removing deliveryAttempt) is a desired behavior because you can still retry on the consuming side regardless of transaction-id-prefix.

2. Why this producer config is affecting [KafkaMessageDrivenChannelAdapter](https://github.com/spring-projects/spring-integration-kafka/blob/327286115911987afef221a9a8eeed00387141bb/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageDrivenChannelAdapter.java#L451), which seems to be the consuming side from the channel. They seem totally disconnected as producer config is destined to Kafka topic and KafkaMessageDrivenChannelAdapter is applied between Kafka Topic to @StreamListener. Debugging through KafkaMessageDrivenChannelAdapter, why RetryTemplate becomes null when transaction-id-prefix is stated in application.yml is another mystery on this whole behavior.

**Comment by jskim1991** [comment]
Hello,

I am using Spring Cloud Stream Binder Kafka for exactly-once semantics. 

I only supply configs through application.yml and I don't override any beans related to Spring Cloud Stream or Spring Kafka currently.

I was looking at the reference and found config for transactional producer : 
spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix.

However, when that option is set to some value (let's say "test-tx-id-"), I noticed that on the Consumer side (@StreamListener), there is no deliveryAttempt field in Kafka Header. Consumer side would look as follows.


```
@StreamListner(SourceBinding.INPUT)
public void listen(Message<String> message) {
    ... do something
}
```


deliveryAttempt has been very helpful to me in terms of debugging and finding out if a received message was retried or not. I am not sure if this(transaction-id-prefix removing deliveryAttempt) is a desired behavior in this library. Also, I am very confused as to why this producer config is affecting [KafkaMessageDrivenChannelAdapter](https://github.com/spring-projects/spring-integration-kafka/blob/327286115911987afef221a9a8eeed00387141bb/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageDrivenChannelAdapter.java#L451), which seems to be the consuming side from the channel.

**Comment by garyrussell** [comment]
Retry (via a `RetryTemplate`) is disabled when transactions are being used. This is because it is not generally desirable to retry within the scope of a transaction. Instead, the exception is thrown back to the listener container which is configured with an `AfterRollbackProcessor` which re-seeks the record so that it is refetched from Kafka.

The retries are handled by the after rollback processor. Even though the after rollback processor keeps state; since the record is re-fetched from Kafka on the next poll; the retry state is not known by the listener container.

Feel free to open a new feature issue against [spring-kafka](https://github.com/spring-projects/spring-kafka/issues) and I'll see if there is something we can do.

**Comment by jskim1991** [comment]
@garyrussell Thank you for your reply. 
Based on your statements, I was able to test my consumers with and without transaction-id-prefix to see how they behave differently. With transaction, I did get a good sense of why it would not use RetryTemplate. 

But there are still some confusions on your comments.

> For exactly once semantics, the transaction is started by the consumer.

Based on my understanding of exactly-once semantics, it seemed mostly focused on the producer side because it needs configurations for retries, idempotence, ack and the consumer needs the configurations for isolation level of read committed, and maybe manual commit. So it seems like transaction starts between a producer and broker before it gets to the consumer. So I m having a hard time understanding why transaction is started by the consumer?

> The retries are handled by the after rollback processor. Even though the after rollback processor keeps state, since the record is re-fetched from Kafka on the next poll, the retry state is not known by the listener container.

I noticed that my failing @StreamListener kept on retrying, which was my intent. But without deliveryAttempt, is there a possible way that I can just look at the headers or payload to distinguish this is retried or not. I am guessing there is no way for that out of the box because it re-fetches.

Lastly, I am having a hard time finding clear instructions on how to apply transactions within the code using spring-cloud-stream-binder-kafka. When I start my spring boot app, i was able to see logs "Instantiated transactional producer" when binding producers. And for consumers, when my @StreamListener fails with an exception, I noticed "Transaction rolled back ...". So I assume transaction is now applied on both producer and consumer without any @Transactional or KafkaTransactionManager defined explicitly in my code? Would that be a safe assumption or is @Transactional required on some method or class just like database transactions?

Please let me know.

Thanks,

**Comment by garyrussell** [comment]
For exactly once semantics, the sequence is as follows:

    beginTx -> send -> sendOffsetToTransaction -> commitTx

In Spring, by default, this is:

    container: getProducerForThisGroupTopicPartition
    container: producer.beginTx
    container: call listener
    listener: producer.send() // indirectly
    container: producer.sendOffsetsToTransaction
    container: producer.commitTx

In other words, to get exactly once, the offset is committed via the producer, within the scope of the transaction. If it worked the way you assumed:

    container: getProducerForThisGroupTopicPartition
    container: producer.beginTx
    container: call listener
    listener: producer.send() // indirectly
    container: consumer.commitOffset
    container: producer.commitTx

The offset commit is not a participant in the transaction and therefore exactly once guarantees are lost.

There **is a way to do what you want**, but it means you would have to add some code to your listener to manage the transaction and send the offsets instead of the container managing it for you.

Let me know if you want me to show you how.

However, this will only work if you do the send within the listener and it won't work with a `@SendTo` reply.

>I am guessing there is no way for that out of the box because it re-fetches.

Correct, but with some changes to Spring Kafka, we could do something since the after rollback processor has the information we need to populate the header; it would take some time to implement and even longer to get into the binder.

**Comment by garyrussell** [comment]
I just re-read your question:

```java
@StreamListner(SourceBinding.INPUT)
public void listen(Message<String> message) {
    ... do something
}
```

This is a sink (consumer-only) method.

If you are not actually sending any messages to Kafka after consuming, then exactly once semantics don't apply at all and you shouldn't enable transactions for that binding.

Exactly once semantics only apply to `read->process->send` applications, and then only the whole flow is "exactly once".

The `read->process` steps are "at least once".

**Comment by jskim1991** [comment]
@garyrussell Thank you for detailed explanation. In terms of the sequence you explained, I was going to point out as well that would be the case of `read->process->send`.

We have some use cases of that but majority of it would be 
`producers: send` 
`consumers: read -> process`

I think that is why I was confused at first place. Now your comments make a lot of sense.

I was thinking of exactly-once semantics in different manner.
What I was hoping was a scenario like below
`producer: send -> transient error -> retry until broker gets it`
`consumer: read -> process (once only)`

If this case is not exactly-once, what would that be? Maybe idempotent producer would just solve this ?

**Comment by garyrussell** [comment]
Idempotent producers don't have to be transactional 

**`enable.idempotence`**: When set to 'true', the producer will ensure that exactly one copy of each message is written in the stream. If 'false', producer retries due to broker failures, etc., may write duplicates of the retried message in the stream. Note that enabling idempotence requires `max.in.flight.requests.per.connection` to be less than or equal to 5, `retries` to be greater than 0 and `acks` must be 'all'. If these values are not explicitly set by the user, suitable values will be chosen. If incompatible values are set, a ConfigException will be thrown.

But transactional producers must have that property set.

**`transactional.id`**: The TransactionalId to use for transactional delivery. This enables reliability semantics which span multiple producer sessions since it allows the client to guarantee that transactions using the same TransactionalId have been completed prior to starting any new transactions. If no TransactionalId is provided, then the producer is limited to idempotent delivery. Note that `enable.idempotence` must be enabled if a TransactionalId is configured. The default is null, which means transactions cannot be used. Note that, by default, transactions require a cluster of at least three brokers which is the recommended setting for production; for development you can change this, by adjusting broker setting transaction.state.log.replication.factor.

If you are publishing records one at a time and want idempotency then the first property should be enough. If you want to publish multiple records atomically (and idempotently) then you need transactions.

On the consumer side, there are no exactly once guarantees; you are on your own to implement idempotency; but this is relatively easy, just store the `topic/partition/offset` along with the data and check that you haven't already processed this record. The topic/partition/offset are available in the `Message<?>` headers.

It is a common mnisunderstanding to believe that Kafka exactly once is a silver bullet; the guarantees only apply to Kafka itself; if the `process` step involves, say, storing to a DB, then you need your own code to deal with duplicate deliveries.

**Comment by jskim1991** [comment]
@garyrussell Thank you so much for your help 👍

**Comment by garyrussell** [comment]
Glad to help; I went ahead and [opened an issue in spring-kafka](https://github.com/spring-projects/spring-kafka/issues/1402).
