### ISSUE TITLE
Cannot configure Kafka through java API

### ISSUE THREAD

**Issue by joelmarty** [spring-cloud/spring-cloud-stream-binder-kafka#87]
Hi,

I want to use a kafka cluster on a cloudfoundry instance (messagehub on bluemix). To configure the service through VCAP_SERVICES, I created a set of ServiceInfo / ServiceInfoCreator and a MessageHubServiceConnectorCreator that extracts the service configuration, registers it as a cloud service and exposes it to the ApplicationContext as a KafkaBinderConfigurationProperties bean.

In a configuration class I have the following method:
```
    @Bean
    public KafkaBinderConfigurationProperties kafkaConfig() {
        KafkaBinderConfigurationProperties service = connectionFactory()
                .service(messageHubService, KafkaBinderConfigurationProperties.class);
        log.info("using kafka brokers: {}", service.getBrokers());
        return service;
    }
```
The problem I have is that it doesn't work as it produces the following error message on start:

> Field configurationProperties in org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration required a single bean, but 2 were found:
	- spring.cloud.stream.kafka.binder-org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfigurationProperties: a programmatically registered singleton	- kafkaConfig: defined by method 'kafkaConfig' in class path resource [com/intesens/CloudConfiguration.class]

Is there any way to block the creation of the first KafkaBinderConfigurationProperties bean or to make my bean the sole instance of this type?

I tried marking the bean as @Primary but I get another exception later in the KafkaBinderJaasInitializerListener class where onApplicationEvent will retrieve the first bean and since it has no Jaas Configuration it does not create the temporary jaas file.

Am I even doing this right?

**Comment by mbogoevici** [comment]
Rather than creating a new `KafkaBinderConfigurationProperties`  bean - which is likely to clash with the one that Spring Boot creates as a result of the `@ConfigurationProperties` annotation, it would be simpler just to read the values from VCAP_SERVICES and assign them to Spring Stream properties.

See - http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.html for details 

So `application.properties` can for instance have something like (for example)

```
spring.cloud.stream.binder.kafka.brokers=${vcap.services.kafka.etc:localhost}
```

(largely depends on the VCAP_SERVICES structure)

**Comment by joelmarty** [comment]
Indeed, it works much better like this! this is solved for me but some documentation would make it more clear on how to proceed

**Comment by mbogoevici** [comment]
Sure, thanks for the suggestion!
