### ISSUE TITLE
Metrics Issue with Multiple Consumer concurrency

### ISSUE THREAD

**Issue by kadkin** [spring-cloud/spring-cloud-stream-binder-kafka#880]
customer_fetch_manager_metrics_records_consumed_total (total number of records used). shows only one thread when you set the value of `spring.cloud.stream.bindings.input.consumer.concurrency` `> 1`

old issues https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/862, with the parameter `concurrency`

reproduce the problems as in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/862, only with the concurrency parameter
[cloud_demo1.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4477105/cloud_demo1.zip)

**Comment by sobychacko** [comment]
@kadkin I see that you have the partition properties as commented out. By default, it then creates a topic with a single partition. With a single partition, if you have concurrency set to more than `1`, it will not have any effect. Could you increase your partition count to 2 and then set the concurrency to 2? The last time I ran this (from the other issue you mentioned ^^) with the example, it worked as expected.

**Comment by kadkin** [comment]
sorry for the long answer
I have created a topic manually with 4 partitions.

**Comment by sobychacko** [comment]
@kadkin This issue is resolved through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/4159217023eff291e5df683e1c52832e066b6a58. For Boot 2.3.x, the metrics are directly coming natively from Micrometer and for Boot 2.2.x, they are coming from the binder based implementation, which was the topic of this issue. This implementation is now streamlined to reflect the native Micrometer implementation.
